services:
  - type: web
    name: centre-mandela
    env: node
    plan: free
    region: frankfurt  # Tu peux changer en 'oregon', 'singapore' selon ta localisation
    buildCommand: "cd client && npm install && npm run build"
    startCommand: "cd client && npm run preview -- --host 0.0.0.0 --port $PORT"
    branches:
      - main
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: "https://api-centre-mandela.com"
    buildFilter:
      paths:
        - client/**
    autoDeploy: true

build:
  nodeVersion: 20.14.0  # Spécifie une version compatible et stable
