- type: web
  name: centre-mandela-backend
  env: node
  plan: free
  rootDir: .
  buildCommand: npm install && npm run build:server
  startCommand: node server/dist/index.js
  branches:
    - main
  envVars:
    - key: NODE_ENV
      value: production
    - key: PORT
      value: 10000
  buildFilter:
    paths:
      - server/**
