services:
  - type: web
    name: centre-mandela-frontend
    env: node
    plan: free
    buildCommand: |
      cd client
      npm install
      npm run build
    startCommand: |
      cd client
      npm run preview -- --host 0.0.0.0 --port $PORT
    branches:
      - main
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: "https://centre-mandela-backend.onrender.com"
    buildFilter:
      paths:
        - client/**

  - type: web
    name: centre-mandela-backend
    env: node
    plan: free
    buildCommand: |
      cd server
      npm install
      npm run build
    startCommand: node server/dist/index.js  # OK si dist est dans /server/dist
    branches:
      - main
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - server/**
